### PR TITLE
Live Currency Improvement + greek 3x

### PR DESCRIPTION
**Pull request by konstantinosbotonakis**
* Instead of a generic 403 error in case Forex is not enabled, now it loads the view showing a message that Forex is not enabled.

image

* Added Greek Language - There are some not great translations as plural doesn't work the same with (s) like English does.

### CODE REVIEW

**Review by farhadrahmanii — APPROVED** [review]

**Comment by andrewdwallo** [comment]
@konstantinosbotonakis I think it would be better to just hide the navigation menu item for Live Currency if Forex isn't enabled. Make sure the abort in mount goes back as well.

`shouldRegisterNavigation` check is not working I think because I am using the navigation builder. You are going to have to apply this in the `FilamentCompaniesServiceProvider`:
```php
NavigationItem::make(LiveCurrency::getNavigationLabel())
                                    ->group(LiveCurrency::getNavigationGroup())
                                    ->parentItem(LiveCurrency::getNavigationParentItem())
                                    ->icon(LiveCurrency::getNavigationIcon())
                                    ->activeIcon(LiveCurrency::getActiveNavigationIcon())
                                    ->isActiveWhen(fn (): bool => request()->routeIs(LiveCurrency::getNavigationItemActiveRoutePattern()))
                                    ->sort(LiveCurrency::getNavigationSort())
                                    ->url(LiveCurrency::getNavigationUrl())
                                    ->visible(LiveCurrency::shouldRegisterNavigation()),
```

**Comment by konstantinosbotonakis** [comment]
@andrewdwallo good suggestion but in case we hide options from main menu, we should be able to enable them via admin. 
AFAIK Forex cannot be enabled via admin settings, only as ENV var before spin up, right?

**Comment by konstantinosbotonakis** [comment]
Also I can see you approved the changes, but I don't have write access, so I can't merge.

**Comment by andrewdwallo** [comment]
@konstantinosbotonakis I didn't approve anything, @farhadrahmanii seemed to approve it although I'm not sure how he can do that. Might need to change some settings for this repo. And yes, that is correct, I am the only one able to merge. I'm sure you can understand why I wouldn't allow people who I don't know to merge whenever they want...

**Comment by konstantinosbotonakis** [comment]
Sure no problem. 
I didn't expect to get write access @andrewdwallo

**Comment by andrewdwallo** [comment]
I'll take a look at this in a little while, I'm currently busy at the moment.

**Comment by andrewdwallo** [comment]
> @andrewdwallo good suggestion but in case we hide options from main menu, we should be able to enable them via admin. AFAIK Forex cannot be enabled via admin settings, only as ENV var before spin up, right?

No we shouldn't be able to enable this via an Admin panel. This should be based on whether its enabled via the config or not, at least for now.

**Comment by konstantinosbotonakis** [comment]
Ok got it. 
I thought because the project is named and focused on SaaS that settings might be able to be toggled via admin users.

**Comment by andrewdwallo** [comment]
> Ok got it. I thought because the project is named and focused on SaaS that settings might be able to be toggled via admin users.

It depends on what the company who owns the SaaS wants to do. For example, almost all Accounting Software I know of provide Live Currency Exchange rates by default - not on a per user basis.

**Pull request closed without merging**
